### ISSUE TITLE
kn quickstart kind - Error: creating cluster: docker not running

### ISSUE THREAD

**Issue by giulianisanches** [knative-extensions/kn-plugin-quickstart#408]
Hello,

I'm trying to use the quickstart plugin to get knative running and learn more about this tool.

I have podman 4.4.4 installed. The podman machine is running and I'm able to create a kind cluster running `kind create cluster`:

```shell
~
❯ kind create cluster
enabling experimental podman provider
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.26.3) 🖼
 ✓ Preparing nodes 📦
 ✓ Writing configuration 📜
 ✓ Starting control-plane 🕹️
 ✓ Installing CNI 🔌
 ✓ Installing StorageClass 💾
Set kubectl context to "kind-kind"
You can now use your cluster with:

kubectl cluster-info --context kind-kind

Have a nice day! 👋

~
❯
```

But when I try to run the command `kn quickstart kind`, i get the following error:

```shell
~
❯ kn quickstart kind
Running Knative Quickstart using Kind
Error: creating cluster: docker not running
Usage:
  kn-quickstart kind [flags]

Flags:
  -h, --help                        help for kind
      --install-eventing            install Eventing on quickstart cluster
      --install-serving             install Serving on quickstart cluster
  -k, --kubernetes-version string   kubernetes version to use (1.x.y) or (kindest/node:v1.x.y)
  -n, --name string                 kind cluster name to be used by kn-quickstart (default "knative")

creating cluster: docker not running
Error: exit status 1

~
❯
```

This is the S.O. version for the podman machine:

```shell
~
❯ podman machine ssh
Connecting to vm podman-machine-default. To close connection, use `~.` or `exit`
Fedora CoreOS 37.20230401.2.0
Tracker: https://github.com/coreos/fedora-coreos-tracker
Discuss: https://discussion.fedoraproject.org/tag/coreos

[core@localhost ~]$ uname -a
Linux localhost.localdomain 6.2.8-200.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Mar 22 19:11:02 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
[core@localhost ~]$ exit
logout

~
❯
```

**Comment by psschwei** [comment]
Quickstart has a dependency on Docker right now as we run a few `docker` commands under the hood. 

In theory (I haven't tested this, but it _could_ work), an `alias docker=podman` may be able to get around that. Or if you'd be interested in submitting a fix to make quickstart more agnostic on docker/podman, a PR would be very welcome :smile:

**Comment by giulianisanches** [comment]
I will fork the repository and try to figure out what's going on and see if i'm able to open a PR for this ;)

**Comment by giulianisanches** [comment]
Just to keep some history here, using alias is a little bit tricky, as we can see [here](https://stackoverflow.com/questions/44382433/why-bash-alias-doesnt-work-in-scripts).

Summarizing:

- aliases are not expanded when the shell is not interactive (and i think that is the case for the command `exec.Command("docker", "stats", "--no-stream")`).
- You can make it to propagate if you set an option at the beginning of your script: `shopt -s expand_aliases`
- You can also make it work if instead of `alias=` you create a function: `function docker() { podman $@ }` ( i have tested this and it works ).

Anyway, playing around the `kind.go` code to create a fix in the plugin itself :)

**Comment by mfreeman451** [comment]
Has anyone considered using `ko-build` here?

**Comment by matzew** [comment]
@giulianisanches I have installed the `podman-docker` package on my fedora, which creates a symbolic link to the `podman` binary.

I am however able to create a `kind` cluster with latest (I tried only local build) of the quickstart.

@psschwei my PR 525 helped w/ the creation of the registry - which is a bit different from docker VS podman perspective
