### ISSUE TITLE
question: why not create local registry by default

### ISSUE THREAD

**Issue by xiangpingjiang** [knative-extensions/kn-plugin-quickstart#441]
After run 

`kn quickstart kind`

I got an error message, " failed to connect local registry to kind cluster"

Then I run 
`kn quickstart kind  --registry`

It worked

Kind version is: 0.17.0

kn Version:      v1.11.0

**Comment by ehudyonasi** [comment]
because of previous issue #393, users were running with podman as container engine and it is not officially supported. So it was decided that as best solution it would not be enabled by default.
