### ISSUE TITLE
Delete plugin to do a clean install

### ISSUE THREAD

**Issue by rkochar** [knative-extensions/kn-plugin-quickstart#508]
I want to do a clean install of the plugin because I appear to have messed something up. I do not see a delete script or a delete flag in `hack/build.sh`. Thanks!

**Comment by psschwei** [comment]
If you're trying to delete a released version of the plugin, you just need to delete the binary, something like `which kn-quickstart` to find the binary and then `rm /path/to/kn-quickstart` to delete it. If you used `brew` to install, then you'd need to use their [uninstall comamnd](https://docs.brew.sh/Manpage#uninstall-formula).

If you're trying to build from source, the binaries are created in the main project directory, so you should be able to remove them with something like `rm /path/to/kn-plugin-quickstart/kn-quickstart*` 

If you're trying to do something else, then let us know what that something else is :smile:
