### ISSUE TITLE
Enhancement: add `--extensions` to capture supported 3rd party tools to install alongside Knative components

### ISSUE THREAD

**Issue by dsimansk** [knative-extensions/kn-plugin-quickstart#526]
> I would prefer something like `--extensions camel`. That could potentially server for additional 3rd party installations. But not a hard opinion, we probably won't grow this list to unmanageable state.

That should substitute specific flags, e.g. `--install-camel` to generic array `--extensions camel,somethingOther`.

_Originally posted by @dsimansk in https://github.com/knative-extensions/kn-plugin-quickstart/pull/521#discussion_r1647390872_

**Comment by psschwei** [comment]
I think it's worth noting that quickstart wasn't intended to support too much configuration (more like spin up a local cluster and install serving and eventing). We had planned to leave more advanced install options to do either via yaml or the operator. 

That said, I'm not opposed to changing that scope, especially if there's a want/need for more configuration with quickstart.
