### ISSUE TITLE
containerd deprecated CRI hosts config

### ISSUE THREAD

**Issue by matzew** [knative-extensions/kn-plugin-quickstart#528]
The old CRI config pattern for specifying registry.mirrors and registry.configs has been DEPRECATED.

See here:
* https://github.com/kubernetes-sigs/kind/issues/2875
* https://github.com/kubernetes/kubernetes/issues/110312

we use it in our `kind.go` file:
https://github.com/knative-extensions/kn-plugin-quickstart/blob/main/pkg/kind/kind.go#L314

Looks like we need to change and create a directory with a `hosts.toml` file for each host

**Comment by matzew** [comment]
@psschwei do you know if these are really needed?

https://github.com/knative-extensions/kn-plugin-quickstart/blob/main/pkg/kind/kind.go#L316-L321

**Comment by psschwei** [comment]
IIRC the node port was to expose the kourier service ([link](https://github.com/knative-extensions/kn-plugin-quickstart/blob/136c4ab40ac5e0d6a4446816b8519a53acc1a720/pkg/install/install.go#L72)), so we could probably use the kind ingress or something else instead and remove that.

I think we'd want to keep the kubernetes version option and the extra mounts option (the latter was just added recently).
